/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FitfabButton {
        "label": string;
        "variant": 'primary' | 'secondary' | 'disabled';
    }
}
declare global {
    interface HTMLFitfabButtonElement extends Components.FitfabButton, HTMLStencilElement {
    }
    var HTMLFitfabButtonElement: {
        prototype: HTMLFitfabButtonElement;
        new (): HTMLFitfabButtonElement;
    };
    interface HTMLElementTagNameMap {
        "fitfab-button": HTMLFitfabButtonElement;
    }
}
declare namespace LocalJSX {
    interface FitfabButton {
        "label"?: string;
        "variant"?: 'primary' | 'secondary' | 'disabled';
    }
    interface IntrinsicElements {
        "fitfab-button": FitfabButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "fitfab-button": LocalJSX.FitfabButton & JSXBase.HTMLAttributes<HTMLFitfabButtonElement>;
        }
    }
}
